apiVersion: v1
kind: Service
metadata:
  name: go-server-calculator-svc
  labels:
    app: go-server-calculator
spec:
  type: NodePort
  selector:
    app: go-server-calculator
  ports: 
  - protocol: TCP
    port: 8080
    targetPort: 8080
