pipeline {
    agent any
    
    stages {
        stage ('Clone Repository') {
            steps {
            	git branch: 'master', url: "https://github.com/henrik-olvr/go-server-calculator.git"
            }
        }
        stage ('Deploy to Kubernetes Cluster') {
            steps {
                sh """
                #!/bin/bash
                kubectl apply -f k8s/deployment.yaml
                kubectl apply -f k8s/service.yaml
                """
            }
        }
        stage ('Getting Service IP') {
            steps {
                sh 'minikube service go-server-calculator-svc'
            }
        }
    }
}
