pipeline {
    agent any
    
    stages {
        stage ('Clone Repository') {
            steps {
            	git branch: 'master', url: "https://github.com/henrik-olvr/go-server-calculator.git"
            }
        }
        stage ('Deploy to Kubernetes Cluster') {
            steps {
                sh """
                #!/bin/bash
                cd ..
                minikube start
                kubectl apply -f k8s/deployment.yaml
                kubectl apply -f k8s/service.yaml
                minikube service go-server-calculator-svc
                """
            }
        }
    }
}
